const ERROR_NO_TOKENS_MINTED: felt252 = 'No tokens minted';
const ERROR_ZERO_AMOUNT: felt252 = 'Amount cannot be zero';
const ERROR_UNAUTHORIZED: felt252 = 'Unauthorized';
const ERROR_ALREADY_WITHDRAWN: felt252 = 'Already Withdrawn';
const ERROR_NO_TOKENS_SOLD: felt252 = 'No tokens sold';
const ERROR_NOT_ORDER_OWNER: felt252 = 'Not order owner';
const ERROR_INVALID_ADDRESS: felt252 = 'Invalid address';
const ALREADY_WITHDRAWN: felt252 = 'Order has been withdrawn';
const ERROR_INVALID_TOKEN: felt252 = 'Invalid token address';